using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("MyCompany")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("MyCompany")]
[assembly: AssemblyProduct("MyCompany Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © MyCompany 2012")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("MyCompany.Scripts._System.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf-resources.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf-extensions.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.touch.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.touch-charts.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf-resources.en_US.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf-menu.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.MicrosoftAjax.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.MicrosoftAjaxWebForms.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.AjaxControlToolkit.js", "text/javascript")]
[assembly: WebResource("MyCompany.Scripts.daf-membership.js", "text/javascript")]
[assembly: WebResource("MyCompany.Theme.Aquarium.css", "text/css", PerformSubstitution=true)]
[assembly: WebResource("MyCompany.Theme.Acrobat.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ActionBarBg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ActionBarDiv.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ActionGroupBg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.AddBookmark.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.AdvancedSearch.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.arrow-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.arrow-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ArrowBkg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Attach.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Attention.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.BACK.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Bullet.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Calendar.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.CheckMark.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.CheckMark2.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.CheckMarkLarge.GIF", "image/GIF")]
[assembly: WebResource("MyCompany.Theme.Close.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.DataSheet.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Delete.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.DropArrow.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Edit.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.EditMode.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Erase.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Excel.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.EXCLAIM.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ExportCsv.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ExportRowset.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ExportRss.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Filter.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.FilterOff.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.FilterOffDisabled.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.FORWARD.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.HeaderBg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.HeaderBgActive.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.html-editor-buttons.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.ICONGO.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Import.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.Import2.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.Information.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Maximize.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.MenuBg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.MenuBgLarge.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Minimize.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.MultiPage.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Navigate.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.NavShape.jpg", "image/jpg")]
[assembly: WebResource("MyCompany.Theme.NavStrip.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.New.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.NewLarge.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ObjectRef.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.PageContentRightSide.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.PageHeader.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ParaHeaderBkg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Paste.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.PopupArrow.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Print.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.QuickFind.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Refresh.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.Save.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SaveLarge.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Search.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Search.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.SearchPlusMinus.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.SettingsGraphic.jpg", "image/jpg")]
[assembly: WebResource("MyCompany.Theme.SiteActionsActiveTab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SiteActionsInactiveTab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SortAZ.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SortDown.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SortUp.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.SortZA.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.StatusBar.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-animated-overlay.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_flat_0_aaaaaa_40x100.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_flat_75_ffffff_40x100.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_glass_55_fbf9ee_1x400.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_glass_75_dadada_1x400.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_glass_75_e6e6e6_1x400.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_glass_95_fef1ec_1x400.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-bg_highlight-soft_75_cccccc_1x100.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-icons_2e83ff_256x240.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-icons_454545_256x240.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-icons_888888_256x240.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.syst-ui-icons_cd0a0a_256x240.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.tab-active-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-left-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-right-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-active.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-active-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-active-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-active.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-hover-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-hover-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-hover.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-bottom.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-left-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-right-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-hover.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-left-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-left.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-line.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-right-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-right.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-verticalleft.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab-verticalright.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.tab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TabsActiveTab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TabsBar.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TabsInactiveTab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TabsSelectedTab.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TaskBoxBkg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TaskBullet.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.TopShape.jpg", "image/jpg")]
[assembly: WebResource("MyCompany.Theme.TreeControls.png", "image/png")]
[assembly: WebResource("MyCompany.Theme.Undo.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.ViewNameBg.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Wait.gif", "image/gif")]
[assembly: WebResource("MyCompany.Theme.Word.gif", "image/gif")]
